# 端口号
server:
  port: 8880
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cdb-3t2y1qjs.sql.tencentcdb.com:59206/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: gg1206245X
  #    redis配置
  redis:
    host: r-uf6j7jxa135iau2ycspd.redis.rds.aliyuncs.com
    port: 6379
    username: r-uf6j7jxa135iau2ycs
    password: redisRoot123
# 配置mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml