# 端口号
server:
  port: 8880
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wiki
    password: wiki
# 配置mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml